export const LIBERIA_COUNTIES = [
  'Bomi',
  'Bong',
  'Gbarpolu',
  'Grand Bassa',
  'Grand Cape Mount',
  'Grand Gedeh',
  'Grand Kru',
  'Lofa',
  'Margibi',
  'Maryland',
  'Montserrado',
  'Nimba',
  'Rivercess',
  'River Gee',
  'Sinoe',
] as const;

export const LIBERIA_DISTRICTS: Record<string, readonly string[]> = {
  Bomi: ['Dowein', 'Klay', 'Senjeh', 'Suehn Mecca', 'Tehr'],
  Bong: [
    'Boinsen',
    'Fuamah',
    'Jorquelleh',
    'Kokoyah',
    'Kpaai',
    'Panta-Kpa',
    'Salala',
    'Sanayea',
    'Suakoko',
    'Tukpahblee',
    'Yeallequelleh',
    'Zota',
  ],
  Gbarpolu: ['Belleh', 'Bopolu', 'Bokomu', 'Gbarma', 'Kongba'],
  'Grand Bassa': [
    'Commonwealth',
    'District #1',
    'District #2',
    'District #3',
    'District #4',
    'Nekreen',
    'St. John River',
  ],
  'Grand Cape Mount': ['Commonwealth', 'Garwula', 'Gola Konneh', 'Porkpa', 'Tewor'],
  'Grand Gedeh': ['Gbarzon', 'Konobo', 'Tchien'],
  'Grand Kru': [
    'Barclayville',
    'Bleebo',
    'Bolloh',
    'Buah',
    'Dorbor',
    'Dweh',
    'Felo-Jekwi',
    'Fenetoe',
    'Forpoh',
    'Garraway',
    'Gee',
    'Grand Cess Wedabo',
    'Upper Jloh',
    'Lower Jloh',
    'Kpi',
    'Nrokwia-Wesldow',
    'Penicess',
    'Trenbo',
    'Wlogba',
  ],
  Lofa: ['Foya', 'Kolahun', 'Salayea', 'Vahun', 'Voinjama', 'Quardu Gboni', 'Zorzor'],
  Margibi: ['Firestone', 'Gibi', 'Kakata', 'Mambah-Kaba'],
  Maryland: ['Barrobo', 'Pleebo/Sodeken'],
  Montserrado: ['Careysburg', 'Commonwealth', 'Greater Monrovia', 'St. Paul River', 'Todee'],
  Nimba: [
    'Boe & Quilla',
    'Buu-Yao',
    'Doe',
    'Garr Bain',
    'Gbehlageh',
    'Gbi & Doru',
    'Gbor',
    'Kparblee',
    'Leewehpea-Mahn',
    'Meinpea-Mahn',
    'Sanniquellie-Mahn',
    'Twan River',
    'Wee-Gbehy-Mahn',
    'Yarmein',
    'Yarpea Mahn',
    'Yarwein Mehnsonnoh',
    'Zoe-Gbao',
  ],
  Rivercess: [
    'Bearwor',
    'Central RiverCess',
    'Doedain',
    'Fen River',
    'Jo River',
    'Norwein',
    'Sam Gbalor',
    'Zartlahn',
  ],
  'River Gee': [
    'Chedepo',
    'Gbeapo',
    'Glaro',
    'Karforh',
    'Nanee',
    'Nyenawliken',
    'Nyenebo',
    'Potupo',
    'Sarbo',
    'Tuobo',
    'Webbo',
  ],
  Sinoe: [
    'Bodae',
    'Bokon',
    'Butaw',
    'Dugbe River',
    'Greenville',
    'Jaedae',
    'Jaedepo',
    'Juarzon',
    'Kpayan',
    'Kulu Shaw Boe',
    'Plahn Nyarn',
    'Pynes Town',
    'Sanquin District 1',
    'Sanquin District 2',
    'Sanquin District 3',
    'Seekon',
    'Wedjah',
  ],
};